// voiture-prediction/src/components/Prediction_form.vue
<template>
    <div>
      <h2>Prédiction des Voitures d'Occasion</h2>
      <form @submit.prevent="handleSubmit">
        <input v-model="formData.kilometrage" type="number" placeholder="Kilométrage" />
        <input v-model="formData.annee" type="number" placeholder="Année" />
        <input v-model="formData.marque" type="text" placeholder="Marque" />
        <input v-model="formData.carburant" type="text" placeholder="Type de Carburant" />
        <input v-model="formData.transmission" type="text" placeholder="Transmission" />
        <input v-model="formData.modele" type="text" placeholder="Modèle" />
        <input v-model="formData.etat" type="text" placeholder="État" />
        <button type="submit">Prédire le Prix</button>
      </form>
      <div v-if="prediction">
        <p>Prix estimé : {{ prediction.predicted_price }} €</p>
        <p>Classification : {{ prediction.deal_classification }}</p>
      </div>
    </div>
  </template>
  
  <script>
  import axios from 'axios';
  
  export default {
    data() {
      return {
        formData: {
          kilometrage: 15000,
          annee: 2020,
          marque: '',
          carburant: 'Essence',
          transmission: 'Manuelle',
          modele: '208',
          etat: 'Occasion'
        },
        prediction: null
      };
    },
    methods: {
      async handleSubmit() {
        try {
          const response = await axios.post(
            `${import.meta.env.VITE_API_BASE_URL}/predict_combined`,  // Aligner avec le backend
            this.formData
          );
          this.prediction = response.data;
        } catch (error) {
          console.error("Erreur lors de la prédiction", error);
        }
      }
    }
  };
  </script>
  
  <style scoped>
    /* Ajoutez votre CSS ici */
  </style>

// voiture-prediction/src/PredictionForm.jsx
// PredictionForm.jsx
import { useState } from 'react';
import axios from 'axios';
import {
  Container,
  Typography,
  TextField,
  Button,
  Box,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Slider,
  LinearProgress,
  Card,
  CardContent
} from '@mui/material';

function PredictionForm() {
  const [formData, setFormData] = useState({
    kilometrage: 15000,
    annee: 2020,
    marque: 'Peugeot',
    carburant: 'Essence',
    transmission: 'Manuelle',
    modele: '208',
    etat: 'Occasion',
  });
  const [prediction, setPrediction] = useState(null);
  const [loading, setLoading] = useState(false);

  const marquesDisponibles = [
    'Audi', 'BMW', 'Citroën', 'Dacia', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Jeep',
    'Kia', 'Lexus', 'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan', 'Opel',
    'Peugeot', 'Renault', 'Seat', 'Skoda', 'Smart', 'Subaru', 'Suzuki', 'Tesla',
    'Toyota', 'Volkswagen', 'Volvo'
  ];

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSliderChange = (field) => (event, value) => {
    setFormData({ ...formData, [field]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      setTimeout(async () => {
        const response = await axios.post(
          `${import.meta.env.VITE_API_BASE_URL}/predict_combined`,
          formData
        );
        setPrediction(response.data);
        setLoading(false);
      }, 3000);
    } catch (error) {
      console.error('Erreur lors de la prédiction', error);
      setLoading(false);
    }
  };

  return (
    <Container maxWidth="md">
      <Typography variant="h4" gutterBottom align="center">
        Prédiction des Voitures d&apos;Occasion
      </Typography>

      <Box component="form" onSubmit={handleSubmit} sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <Typography variant="h6">Caractéristiques du Véhicule</Typography>
        <FormControl fullWidth>
          <Typography gutterBottom>Kilométrage (en km)</Typography>
          <Slider
            value={formData.kilometrage}
            onChange={handleSliderChange('kilometrage')}
            min={0}
            max={300000}
            step={1000}
            valueLabelDisplay="auto"
            name="kilometrage"
          />
        </FormControl>
        <FormControl fullWidth>
          <Typography gutterBottom>Année de Mise en Circulation</Typography>
          <Slider
            value={formData.annee}
            onChange={handleSliderChange('annee')}
            min={1980}
            max={2024}
            step={1}
            valueLabelDisplay="auto"
            name="annee"
          />
        </FormControl>

        <FormControl fullWidth>
          <InputLabel>Marque</InputLabel>
          <Select
            name="marque"
            value={formData.marque}
            onChange={handleChange}
          >
            {marquesDisponibles.map((marque) => (
              <MenuItem key={marque} value={marque}>
                {marque}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <TextField
          label="Modèle"
          variant="outlined"
          name="modele"
          type="text"
          value={formData.modele}
          onChange={handleChange}
        />
        <FormControl fullWidth>
          <InputLabel>Transmission</InputLabel>
          <Select
            name="transmission"
            value={formData.transmission}
            onChange={handleChange}
          >
            <MenuItem value="Manuelle">Manuelle</MenuItem>
            <MenuItem value="Automatique">Automatique</MenuItem>
          </Select>
        </FormControl>
        <FormControl fullWidth>
          <InputLabel>Type de Carburant</InputLabel>
          <Select
            name="carburant"
            value={formData.carburant}
            onChange={handleChange}
          >
            <MenuItem value="Essence">Essence</MenuItem>
            <MenuItem value="Diesel">Diesel</MenuItem>
            <MenuItem value="Hybride">Hybride</MenuItem>
            <MenuItem value="Électrique">Électrique</MenuItem>
          </Select>
        </FormControl>
        <TextField
          label="État"
          variant="outlined"
          name="etat"
          type="text"
          value={formData.etat}
          onChange={handleChange}
        />
        <Button variant="contained" color="primary" type="submit" disabled={loading}>
          Prédire le Prix
        </Button>
      </Box>

      {loading && (
        <Box mt={2}>
          <LinearProgress />
          <Typography variant="body2" align="center" mt={2}>
            Prédiction en cours, veuillez patienter...
          </Typography>
        </Box>
      )}

      {prediction && (
        <Card
          sx={{
            maxWidth: 500,
            margin: '20px auto',
            backgroundColor: prediction.deal_classification === 'Bonne affaire' ? '#c8e6c9' : '#ffcdd2'
          }}
        >
          <CardContent>
            <Typography variant="h6" gutterBottom>
              Résultat de la Prédiction
            </Typography>
            <Typography variant="body1">
              Prix Estimé : {prediction.predicted_price} €
            </Typography>
            <Typography variant="body1">
              Classification de l&apos;offre : {prediction.deal_classification}
            </Typography>
          </CardContent>
        </Card>
      )}
    </Container>
  );
}

export default PredictionForm;
